### ISSUE TITLE
Why does the top level table have two “self” link columns?

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#11]
In the example, games has _link and _link _games, which are the same.

Other tables do not have this duplication. They have one _link column for themselves, and the rest link to other tables.

**Comment by kindly** [comment]
This is for consistancy as all tables have:
`_link` and `_link_<main_table_name>`

This has the benefit of always being able to use `using(<main_table_name>)` when doing joins to it, at the cost of duplicating the column.

**Comment by jpmckinney** [comment]
What is the use case of joining the top table to itself? If there is none, then it doesn't seem to be a benefit.

What I see as consistent is that `_link_xxx` always links to each ancestor table.

Seen that way, it is *inconsistent* to have `_link_xxx` in the top table, because it has no ancestors.

**Comment by kindly** [comment]
It is for the use case of every other table to be able to join to the main_table using `using`. However I am not convinced either way so may consider removing.

**Comment by jpmckinney** [comment]
I don't know the implementation of `using` (is it documented?), but I would have assumed that `_link_tablename` from a child table is matched against the ancestor table's `_link` column – such that the root table's `_link_games` isn't used for linking.

**Comment by kindly** [comment]
This has changed so that main table now only has `_link`
