### ISSUE TITLE
Feature request: Feedback to user in CLI (e.g. progress indicator)

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#15]
e.g. https://click.palletsprojects.com/en/5.x/utils/#showing-progress-bars since already using Click.

or https://github.com/tqdm/tqdm as another option.

**Comment by kindly** [comment]
A progress bar would be difficult to make accurate, due to the parsing of JSON and the processing being done in seperate threads.  However a verbose mode where you can see the stage in the process you are makes sense.

**Comment by kindly** [comment]
I think I am going to approach this with logging.

The CLI will have log level `info` which will have information on progress.
Python API will default to `warn`

Configuarble through `FLATTERER_LOG=<level>` enviroment variable.

**Comment by kindly** [comment]
This is done now.  In the CLI the default log level is `info` giving fairly good feedback as to progress.
