### ISSUE TITLE
Various fixtures for "edge" cases

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#17]
Among OCDS publishers, we see all sorts of invalid files. Flatterer currently doesn't give any feedback and returns with a zero (success) exit code in many of these cases, and has unhandled errors in other cases. In some of the cases where it is quiet, it processes a file until it encounters an error and then stops – i.e. producing incomplete output, with no feedback to the user.

# Invalid JSON

```
echo '[' > invalid.json
flatterer --force invalid.json out
```

Produces no CSV file, nearly empty other files (just boilerplate if anything).

Expected: Should have a clear error message (e.g. `The JSON that was provided as input is invalid. No output has been written.`), and no files written.

# Invalid JSON array element

```
[
    {
        "foo": "bar"
    },
    {
        "foo": ""bar"
    }
]
```

It writes data for the first element only.

Expected: Should have a clear error message (e.g. `Element 2 of the main array is invalid JSON. No output has been written for element 2 onward.`).

# Invalid JSON Lines

```
{"foo":"bar"}
{
{"bar":"baz"}
```

```
Traceback (most recent call last):
  File "bin/flatterer", line 8, in <module>
    sys.exit(cli())
  File "site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "site-packages/flatterer/__init__.py", line 115, in cli
    flatten(input_file,
  File "site-packages/flatterer/__init__.py", line 43, in flatten
    flatten_rs(input, output_dir, csv, xlsx,
OSError: SerdeReadError { source: Error("key must be a string", line: 3, column: 1) }
```

It writes data for the first value only.

Expected: Should have a clear error message (e.g. `Value 2 is invalid JSON. No output has been written for value 2 onward.`).

Note: I use "value" because Flatterer supports concatenated JSON, not just JSON Lines (#21).

# Non-UTF-8 file

Save `[{"foo":"€"}]` as Windows 1252.

```
Traceback (most recent call last):
  File "bin/flatterer", line 8, in <module>
    sys.exit(cli())
  File "site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "site-packages/flatterer/__init__.py", line 115, in cli
    flatten(input_file,
  File "site-packages/flatterer/__init__.py", line 43, in flatten
    flatten_rs(input, output_dir, csv, xlsx,
OSError: YAJLishParseError { error: "Error: Malformed Json: invalid utf-8 sequence of 1 bytes from index 1" }
```

Produces no CSV file, nearly empty other files (just boilerplate if anything).

Expected: Should have a clear error message (e.g. `The JSON that was provided as input is not encoded as UTF-8. No output has been written.`), and no files written.

# Illegal Excel characters

```
echo '[{"\u0000": "bar"}]' > illegal.json
env RUST_BACKTRACE=full flatterer --force --xlsx _data/illegal.json out
```

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(0, [0])', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/xlsxwriter-0.3.5/src/worksheet.rs:420:36
stack backtrace:
   0:        0x103dfd714 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8483effd3e9ec544
   1:        0x103e180a4 - core::fmt::write::ha34752bcd39bca36
   2:        0x103df7d7c - std::io::Write::write_fmt::hfc57a6e48a9ddae2
   3:        0x103dff134 - std::panicking::default_hook::{{closure}}::he9aaba83dd453f35
   4:        0x103dfed14 - std::panicking::default_hook::hc87ff103cfd8260f
   5:        0x103dff774 - std::panicking::rust_panic_with_hook::hf890018b6cf19ef5
   6:        0x103dff2c0 - std::panicking::begin_panic_handler::{{closure}}::hc0918e64b5d68f06
   7:        0x103dfdbd4 - std::sys_common::backtrace::__rust_end_short_backtrace::hb99d925d54d4af60
   8:        0x103dff228 - _rust_begin_unwind
   9:        0x103e2ca54 - core::panicking::panic_fmt::hf9e85df46ac02a7d
  10:        0x103e2caf8 - core::result::unwrap_failed::h3b4d980f8618ad59
  11:        0x103c90820 - xlsxwriter::worksheet::Worksheet::write_string::h13a473556bc29807
  12:        0x103c70044 - libflatterer::FlatFiles::write_xlsx::h34bc21d9c7d215d4
  13:        0x103c6cce8 - libflatterer::FlatFiles::write_files::hd4e67029d7f3178f
  14:        0x103c377a4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h22c6a4cd1f80f663
  15:        0x103c3fc08 - std::panicking::try::habfb7204a233339a
  16:        0x103c50124 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h891ed28ee84ee7d4
  17:        0x103e0290c - std::sys::unix::thread::Thread::new::thread_start::hb0ee8a3c2c47a737
  18:        0x1856914ec - _pthread_from_mach_thread_np
Traceback (most recent call last):
  File "bin/flatterer", line 8, in <module>
    sys.exit(cli())
  File "site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "site-packages/flatterer/__init__.py", line 115, in cli
    flatten(input_file,
  File "site-packages/flatterer/__init__.py", line 43, in flatten
    flatten_rs(input, output_dir, csv, xlsx,
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: NulError(0, [0])
```

Expected: Should either:

1. Delete NUL characters, and add this as a documented behavior.
2. Have a clear error message, e.g. `The JSON that was provided as input contains characters that are illegal in Excel files.`

I don't know if maybe more characters from `openpyxl.cell.cell.ILLEGAL_CHARACTERS_RE` (that is, `re.compile('[\\000-\\010]|[\\013-\\014]|[\\016-\\037]')`) will also cause errors. I only tried `\u0001` and that one worked.

# Main "array" is a literal

```
echo '1' > literal.json
flatterer --force literal.json out
```

Produces no CSV file, nearly empty other files (just boilerplate if anything).

Expected: Should have a clear error message (e.g. `The JSON that was provided as input is a <type>, not an array. No output has been written.`), and no files written.

# Main array is empty

```
echo '[]' > array-empty.json
flatterer --force array-empty.json out
```

```
Traceback (most recent call last):
  File "bin/flatterer", line 8, in <module>
    sys.exit(cli())
  File "site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "site-packages/flatterer/__init__.py", line 115, in cli
    flatten(input_file,
  File "site-packages/flatterer/__init__.py", line 43, in flatten
    flatten_rs(input, output_dir, csv, xlsx,
OSError: SerdeReadError { source: Error("EOF while parsing a value", line: 1, column: 0) }
```

Expected: Should have a clear error message (e.g. "The JSON array contains no objects. No output has been written.") without backtrace and without files written.

# Main array contains literals only

```
echo '[1]' > array-literal.json
flatterer --force array-literal.json out
```

Produces no CSV file, nearly empty other files (just boilerplate if anything).

Expected: Should have a clear error message (e.g. "The JSON array contains no objects. No output has been written."), and no files written.

# Main array contains literals and objects

```
echo '[1,{"foo": "bar"}]' > array-mixed.json
flatterer --force array-mixed.json out
```

Produces a CSV file.

Expected: Should have a clear *warning* message (e.g. `WARNING: The JSON array contains a <type>. This value has not been written.`).

# Main "array" is an object

```
echo '{"foo":"bar"}' > object.json
flatterer --force object.json out
```

Produces no CSV file, nearly empty other files (just boilerplate if anything).

Expected: Should have a clear error message (maybe with `The JSON that was provided as input is an object, not an array. No output has been written. Did you mean: flatterer --json-lines <rest of original command> ?`), and no files written.

**Comment by kindly** [comment]
Thanks! that is a very useful list of edge cases.

**Comment by kindly** [comment]
Checlist for fixing the above:

- [ ]  Invalid JSON
- [ ]  Invalid JSON Lines
- [ ]  Non-UTF-8 file
- [ ]  Main "array" is a literal
- [ ]  Main array is empty
- [ ]  Main "array" is an object

**Comment by kindly** [comment]
These are now fixed in 0.10.

**Comment by jpmckinney** [comment]
Awesome! However,

```
echo '[' > invalid.json
flatterer --force invalid.json out
```

and the non-UTF-8 fixture still produce an `out` directory.

---

Noting that the stripping of illegal characters in Excel does not cause collisions, e.g. the following produces two data columns, as expected 👍 

```
[
    {
        "\u0000x": "foo",
        "x": "bar"
    }
]
```

**Comment by kindly** [comment]
@jpmckinney nice spot.  This is fixed now in the lib code so will be in the next release.

**Comment by kindly** [comment]
these should be fixed now.
