### ISSUE TITLE
An array of empty object(s) produces an empty table

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#19]
I don't know if this is by design, but it does not seem useful to have a table with only `_link*` columns.

```json
[
    {
        "foo": [
            {}
        ],
        "bar": [],
        "baz": {}
    }
]
```

`main.csv` (I think this one is okay – the input is just bare)

```
_link,_link_main
1,1
```

`foo.csv` (I think this one is not useful)

```
_link,_link_main
1.foo.0,1
```

Note: As expected, no `bar.csv` file is written, and no `baz` column is written.

**Comment by kindly** [comment]
Sounds fair to remove.

**Comment by kindly** [comment]
They are removed in version 0.11
commit https://github.com/kindly/libflatterer/commit/fe4a0e46841880bc3f88d7267614fc1a4145c6f7
