### ISSUE TITLE
Docs: Flatterer supports concatenated JSON, not just JSON Lines

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#21]
These work fine (thanks to YAJL):

```
{
    "foo": "bar"
}
{
    "foo": "bar"
}
```

```
{"foo":"bar"}{"foo":"bar"}
```

Both yield:

```
_link,_link_concatenated,foo
1,1,bar
2,2,bar
```

It might be good to rename `--json-lines` as well.

https://en.wikipedia.org/wiki/JSON_streaming#Concatenated_JSON

**Comment by kindly** [comment]
Yes it actually uses [serde_json](https://docs.serde.rs/serde_json/struct.StreamDeserializer.html) for `self-delineating` streaming and was aware of this.   I just thought JSONLines was more well known and why I used it as an option name.

If Concatenated JSON is the term that is most used the would be use that, but I am not sure that it is that common yet.

**Comment by jpmckinney** [comment]
Perhaps `--json-stream`? I think jq uses that term.

**Comment by kindly** [comment]
@jpmckinney sadly I had to use two parsers. One for when then the array is in nested object (yaglish) and another for the `json-stream` implementaion `serde_json`.  There is not a single one that does both like in Python.

`--json-stream` sounds good.
