### ISSUE TITLE
How to use preview option from Python library

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#23]
0.9 adds "Lib has preview option, meaning CSV output will optionally only show specified number of lines."

However, I don't see how that option can be configured from within Python. Is it possible?

**Comment by jpmckinney** [comment]
I assume that in the short term I can just feed Flatterer whatever number of inputs I desire, instead of relying on the preview functionality (not sure if preview is doing anything beyond that).

**Comment by jpmckinney** [comment]
Actually, as I think about it more, I assume flatterer reads the full file in preview mode to calculate statistics, but it only prepares output for the given number of preview rows. In that case, the above workaround isn't enough.

**Comment by kindly** [comment]
@jpmckinney the python libarary/cli does not have access to that function yet.  I will try and release a version that does in the next few days.

**Comment by kindly** [comment]
@jpmckinney this has beed added to latest release.

https://flatterer.opendata.coop/options.html#preview
