### ISSUE TITLE
bug: str generator causes TypeError

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#26]
```python
import flatterer

flatterer.flatten(["foo"], dataframe=True)
```

```
File lib/python3.8/site-packages/flatterer/__init__.py:52, in bytes_generator(iterator)
     51 if isinstance(item, str):
---> 52     yield str.encode()
     53 if isinstance(item, dict):

TypeError: descriptor 'encode' of 'str' object needs an argument
```

Should be at minimum `item.encode()` and probably `item.encode("utf-8")`.

**Comment by kindly** [comment]
@jpmckinney agreed

Once changed there needs a test, and JSON string/bytes iterators added to the docs.

**Comment by kindly** [comment]
@jpmckinney this is now fixed, but keeping issue open as if the strings are not valid JSON then the errors are not very clear.

**Comment by jpmckinney** [comment]
Thank you!
