### ISSUE TITLE
pushdown clarification

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#31]
Is it possible to push down only fields from the top-level table, or is it possible to specify a field from a child table to push down to the grandchildren, etc.?

**Comment by kindly** [comment]
@jpmckinney  It should match any field where the key in the object matches. This is for both the parent table or any child tables.

So if you express `id` and the child table has an `id` key that field is pushed down as in the example https://flatterer.opendata.coop/options.html#id3.  There is both `game_id` and `platform_id` in the grandchild. Also in that example `name` is only in the child.

What you can not do currently is to specify you pushdown only for certain cases where that key name exists.  I was thinking that some syntax like jsonpath (without the numbers for array index) could work there e.g `/platform/name` would mean only the `name` at that path would be selected to pushdown.  However, maybe that is overcomplicating things.

**Comment by jpmckinney** [comment]
Ah, thanks for clarifying! Yes, I was wondering if a longer path could be set.

**Comment by kindly** [comment]
Am closing this as I am not sure setting a specific path is useful enough to add.  The worst case at the moment is too many fields will be pushed down (which can be removed by fields.csv).
