### ISSUE TITLE
.pgpass file or environment variable support

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#32]
Is the `.pgpass` file supported? If not, can the connection string be provided via an environment variable, to avoid putting a password in the command-line history?

**Comment by jpmckinney** [comment]
FYI, psycopg2 has `.pgpass` support by virtue of using `libpq` to connect to the database (there is no pgpass-specific code in psycopg2 itself). I don't know what datapackage_convert uses (there are no docs).

**Comment by jpmckinney** [comment]
Looks like the postgres create doesn't support it, and it doesn't use libpq (it re-implements it, basically). https://github.com/sfackler/rust-postgres/issues/729

**Comment by kindly** [comment]
@jpmckinney great idea.  I will add environment support at least.

**Comment by kindly** [comment]
@jpmckinney the docs are here, http://datapackage_convert.opendata.coop/postgres.html but does not cover what libaries are used.

**Comment by jpmckinney** [comment]
Ah, thanks, might be good to link to it from the GitHub repository / add a readme.

**Comment by kindly** [comment]
There is now a way to get connection string from environment variable.

https://flatterer.opendata.coop/options.html#output-formats
