### ISSUE TITLE
[Question] i attended the frictionless meetup, can i ask if i can integrate this with my django app somehow?

### ISSUE THREAD

**Issue by simkimsia** [kindly/flatterer#33]
because i saw the web interface in the meetup during the demo. so i was wondering if it's possible to integrate with my Django app

**Comment by kindly** [comment]
I think you would have to write some kind of frontend yourself.  Flatterer is just a python libarary that could be imported and used but there is not Python frontend for it.

Currently the web frontend https://github.com/kindly/flatterer-web/ is written in Rust too and would be hard to integrate.
