### ISSUE TITLE
"Too many open files (os error 24)" when using --threads 4 or greater (or 0)

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#34]
Using the 2013 JSONL file from https://data.open-contracting.org/en/publication/63

```
flatterer --threads 0 --force -j paraguay_dncp_records_2013.jsonl out
```

**Comment by kindly** [comment]
This is an operating system level error as there is a limit to operating system open file descriptors.  It is working on my 8core/16 thread machine with --threads 0.

You can raise the limits, there are ones at the user level and the system level:
http://woshub.com/too-many-open-files-error-linux/

I do not think I can lower the files that are open in this mode with flatterer.  It will open (`threads*amount of tables`) file descriptors so it could add up to quite a bit.  However, it is likely that it is some other processes are also using a lot and flatterer is just pushing it over the limit as it opens up a lot quickly.

 It may be possible for flatterer, to not hold on to the file descriptors and reopen the file each time, as an option, but I would have to look at performance implications of that.

**Comment by jpmckinney** [comment]
Hmm, on macOS, running:

    launchctl limit maxfiles

yields

    maxfiles    256            unlimited

256 is a soft limit, unlimited is a hard limit. I guess Rust respects the soft limit? There are 65 files that are ultimately being written, so I guess that explains why it errors with 4 threads.

**Comment by jpmckinney** [comment]
Setting `ulimit -n 1024` fixes the issue.

**Comment by jpmckinney** [comment]
I think a note would be good. I don't know if that error can be caught in Rust – if so, a note can be made along with the exception.

**Comment by kindly** [comment]
I have captured the exact error code and gave a clearer error message for that case:

https://github.com/kindly/libflatterer/commit/04cfa739a2155fa7f1c8c7d4ae78f5f90421f904

This will be in the next release.
