### ISSUE TITLE
FYI, `std::sync::mpsc ` now uses `crossbeam-channel`

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#39]
In case you want to simplify a dependency.

https://blog.rust-lang.org/2023/01/26/Rust-1.67.0.html#stdsyncmpsc-implementation-updated

**Comment by kindly** [comment]
Thanks. 
The library is using it for `spmc`  (single producer, multi consumer).  The JSON parsing is done in a single thread (there is no way around this, sadly) and the flattening of each object is shared between multiple threads.  

I think they will add this soon, as the code is there, but it does not seem they have exposed this option yet.
