### ISSUE TITLE
Unable to pip install without Rust toolchain on Windows 11 (x64)

### ISSUE THREAD

**Issue by dslinger-a2** [kindly/flatterer#41]
I'm getting this error message when trying to pip install on Windows 11 (x64). I don't have this issue if I try to replicate in an Ubuntu docker container or on a different pop!_os laptop. It seemed in the readme that the intention is for the wheels to work for Windows. I'm getting the same error when trying to install a number of different older versions of flatterer on this Windows machine. I understand that I can install the Rust toolchain to resolve this but wanted to bring up the issue.

```
Collecting flatterer
  Using cached flatterer-0.18.1.tar.gz (5.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by dslinger-a2** [comment]
And this was with Python v3.10.7

**Comment by kindly** [comment]
@dslinger-a2 thanks for making me aware of this.

It looks like only python 3.9 builds were being made for windows from flatterer version `0.17` and later.  

I am trying to make a new [release now](https://github.com/kindly/flatterer/actions/runs/4613335674) with python 3.8 - 3.11 for windows.

**Comment by dslinger-a2** [comment]
Looks good! Thanks so much @kindly!
