### ISSUE TITLE
What is the significance of `options.threads != 2`?

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#52]
I don't understand what this condition is doing.

https://github.com/kindly/libflatterer/blob/ff4647491ef1f716561d49672cc4bd802e64d9dc/src/lib.rs#L3378-L3382

Added in https://github.com/kindly/libflatterer/commit/4e63ac68628532f9edafa5d94e01442bf5b99e74

**Comment by kindly** [comment]
@jpmckinney I think this is an error that and should not be there.  I think it was me trying to fix #46 when I first noticed it, but I am sure it was there way before that commit. I think it was part of a refactor there.  

I am debating wheather to put `options.threads == 1` as that is the only case where the error truely holds. See discussion #53

**Comment by jpmckinney** [comment]
Changed in https://github.com/kindly/libflatterer/commit/270057acdfb9afff5d98d33b483061adb0e5ddd5
