### ISSUE TITLE
Multithreaded can randomly raise "The JSON provided as input is not an array of objects" for ndjson

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#53]
The code does:

```rust
            let mut count = 0;
            for item in item_receiver.iter() {
                // ...
            }

            if count == 0 && options.threads != 2 {
                return Err(Error::FlattererProcessError {
                    message: "The JSON provided as input is not an array of objects".to_string(),
                });
            }
```

If, by the time a thread starts, the channel becomes empty or is disconnected, then there will be nothing to `iter()`, and therefore `count` will be 0.

At a minimum, the error message is misleading for several reasons.

* When `ndjson` is true, the input is not expected to be an array ("is not an array")
* The error case "not ... of objects" is already handled by:

    ```rust
                if !value.is_object() {
                    return Err(Error::FlattererProcessError {
                        message: format!(
                            "Value at array position {} is not an object: value is `{}`",
                            count, value
                        ),
                    });
                }
    ```

    Though, this message is also incorrect in the case of ndjson, since ndjson works with line numbers, not array positions.

    Even so, the position used is the `count`, which starts at 0 in each thread. This count will not match the line number in the file. You would need to send the line number through the channel for this message to be correct.

All that said, is this error message even needed, at least in the case of ndjson?

**Comment by kindly** [comment]
@jpmckinney 

Yes, this makes sense to skip for `ndjson` and potentially `json-stream` and even to skip for whenever multithreaded is used.

The annoying issue that this error tries to solve, is with the streaming JSON parser that I use. It will not report if there is an array of objects at a certain point, so I have no way to check, without loading the whole file in memory. 
So this error is a proxy to that. So if no objects get streamed, it means that there could not have been an array of objects there.  For multithreaded, sometimes, no objects get streamed as the file is too small, so this error is also wrong for that case.

But I had never thought ndjson would be exempt, but you are right it is. I have not got time this weekend to fix this, but will probably do that in the next week or so.

Funny enough, my current side project, is to try and write a "better" streaming JSON parser, with better errors and I think I could make it a bit faster.  Also, possibly more interestingly, I want it to be able to provide a mapping between a certain json-path and the exact place in the file (or individual object) where that path lives.  This would mean that if you got a list of validation errors from JSONSchema with the JSON paths, you could use them to show where exactly in the file the error actually was, with a line and column number and even some surrounded text around that path.

**Comment by jpmckinney** [comment]
Looks fixed :) https://github.com/kindly/libflatterer/commit/270057acdfb9afff5d98d33b483061adb0e5ddd5
