### ISSUE TITLE
Parsing/conversion error

### ISSUE THREAD

**Issue by alevites** [kindly/flatterer#56]
Running the following file into parquet:

https://developers.humana.com/syntheticdata/Resource/DownloadTOCFile?fileName=2023-09-18_humana-inc-il-lg-humana-ppo-ehdhp-14-cpy_index.json.gz

Produces the following error:

thread 'tokio-runtime-worker' panicked at 'Could not parse number as i64 or f64', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\yajlish-0.4.0\src\parser.rs:142:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "C:\Users\mrfpocadmin\Desktop\MRF\Setup\MRF_to_parquet.py", line 25, in <module>
    output = flatterer.flatten(inputPath, outputPath, csv=False, parquet=True, force=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\flatterer\__init__.py", line 139, in flatten
    flatten_rs(input, output_dir, csv, xlsx, sqlite, parquet,
RuntimeError: task 1 panicked

Caused by:
    task 1 panicked

Location:
    /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\convert\mod.rs:727:9

**Comment by kindly** [comment]
The following command seems to work for me.
```
>>> import flatterer
>>> flatterer.flatten('https://developers.humana.com/syntheticdata/Resource/DownloadTOCFile?fileName=2023-09-18_humana-inc-il-lg-humana-ppo-ehdhp-14-cpy_index.json.gz', 'out', parquet=True, force=True, csv=False)
```

To me, it looks like the file got cut off due to network issue or something.
