### ISSUE TITLE
Invalid JSON error

### ISSUE THREAD

**Issue by alevites** [kindly/flatterer#57]
Running the following file to parquet:

https://developers.humana.com/Resource/DownloadPCTFile?fileType=innetwork&fileName=2023-09-22_54_in-network-rates_1.json.gz

Produces the following error:

Traceback (most recent call last):
  File "C:\Users\mrfpocadmin\Desktop\MRF\Setup\MRF_to_parquet.py", line 25, in <module>
    output = flatterer.flatten(inputPath, outputPath, csv=False, parquet=True, force=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\flatterer\__init__.py", line 139, in flatten
    flatten_rs(input, output_dir, csv, xlsx, sqlite, parquet,
RuntimeError: YAJLish parse error: Invalid JSON due to the following error: Error: Malformed Json: Parse failed due to malformed json: open braces: 1, open brackets: 0

Location:
    /rustc/90c541806f23a127002de5b4038be731ba1458ca\library\core\src\convert\mod.rs:727:9

I used a JSON validator and it passed the check.

**Comment by kindly** [comment]
This command works for me

```
flatterer.flatten('https://developers.humana.com/Resource/DownloadPCTFile?fileType=innetwork&fileName=2023-09-22_54_in-network-rates_1.json.gz', 'out', force=True, csv=False, parquet=True)
```

This also looks like the file is getting cut off for some reason, as the error is showing that not all the brackets have been closed.  I can not think of anything that could cause this.

**Comment by alevites** [comment]
Very strange.  I am actually using the dload module to download the files (for archiving), then pushing them through flatterer, so it must be the download that is breaking the formatting.  Sorry for the stupid questions, appreciate the help!
