### ISSUE TITLE
Document iterator_flatten

### ISSUE THREAD

**Issue by kindly** [kindly/flatterer#6]
Add section to docs that explains the python API better.

**Comment by jpmckinney** [comment]
One use case, which can be documented, is to use this to enrich the data with additional / calculated fields. For example, https://github.com/kindly/flatterer/issues/10 discusses adding unique IDs that are based on data values.

**Comment by jpmckinney** [comment]
I think this is now documented (as `flatten`) https://flatterer.opendata.coop/library.html

**Comment by kindly** [comment]
Yes, thanks this should be closed.
