### ISSUE TITLE
split outputs with many columns?

### ISSUE THREAD

**Issue by tooptoop4** [kindly/flatterer#60]
some target systems have limits on the number of columns in a table ie table can have max 2000 columns

if the top level of the json had 1500 different tags is it possible to make the columns for tag1, tag2...tag750 go to games_part1.csv but the columns for tag751, tag752...tag1500 go to games_part2.csv ? with a designated key tag on both games_part1.csv and games_part2.csv

**Comment by kindly** [comment]
I can not think of an easy way to do this.  I would consider using somthing like https://github.com/jqnatividad/qsv to manipulate the CSVs after produced.
