### ISSUE TITLE
set desired column names?

### ISSUE THREAD

**Issue by tooptoop4** [kindly/flatterer#61]
is there option to rename the column headers in the final csvs?

**Comment by kindly** [comment]
@tooptoop4 

The `fields.csv` file is intended for changing column names.

Documented:
https://flatterer.opendata.coop/index.html#fields-csv
and 
https://flatterer.opendata.coop/options.html#fields-file

You can get the `fields.csv` file by running flatterer against your data and then modifying the field_title column and using it as an input to the next run.
