### ISSUE TITLE
Consider using rust_xlsxwriter instead of xlsxwriter

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#67]
https://github.com/jmcnamara/rust_xlsxwriter by the same author as the [Python original](https://github.com/jmcnamara/xlsxwriter) and the [C library](https://github.com/jmcnamara/libxlsxwriter).

This project currently users a [wrapper](https://github.com/informationsea/xlsxwriter-rs) around that C library.

I'm experiencing hard-to-debug errors like:

```
python: third_party/libxlsxwriter/third_party/dtoa/emyg_dtoa.c:446: emyg_dtoa: Assertion `!(sizeof (value) == sizeof (float) ? __isnanf (value) : sizeof (value) == sizeof (double) ? __isnan (value) : __isnanl (value))' failed.
```

The pure Rust version might be better (or, at least, might be easier to debug).

**Comment by kindly** [comment]
@jpmckinney  It looks like it currently does not support low memory mode, which I think is a requirement for large files. See:  https://github.com/jmcnamara/rust_xlsxwriter/issues/1    Once that is implemented I think this would be good move, as compiling the c version really complicates creating the python wheels.  To be honest this has been the most painful part of flatterer.

I am wondering if there should be an option to use the python version of libxlsxwriter, in this python wrapper (converting from CSV with the field information).  This would be slower but much easier to debug.

**Comment by jpmckinney** [comment]
Aha, good to know. In our case, we can't really go slower – we have lots of big files that already use a lot of CPU.

**Comment by jpmckinney** [comment]
I found a way to reproduce the issue, so I'll open a new issue to keep it separate.

**Comment by jmcnamara** [comment]
> It looks like it currently does not support low memory mode, which I think is a requirement for large files. See: [jmcnamara/rust_xlsxwriter#1](https://github.com/jmcnamara/rust_xlsxwriter/issues/1) Once that is implemented I think this would be good move, as compiling the c version really complicates creating the python wheels.

Low/constant memory mode is now supported in `rust_xlsxwriter` along with large file (>4GB) support.

**Comment by kindly** [comment]
@jmcnamara great, it is now using `rust_xlsxwriter` and everything worked well.

**Comment by jmcnamara** [comment]
@kindly That's great. If there are any issues then @ me hear or open an issue in rust_xlsxwriter.
