### ISSUE TITLE
Fails in Kubernetes pod with only_fields=True

### ISSUE THREAD

**Issue by tianchen98** [kindly/flatterer#69]
I was testing the package in a Kubernetes pod with
```
flatten('s3://<path-redacted>.jsonl.gz', '/tmp/unnest', force=True, tables_csv='/tmp/tables.csv, only_tables=True, fields_csv='/tmp/fields.csv', only_fields=True, ndjson=True)
```
but received the following error message:
```
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libflatterer-0.19.12/src/lib.rs:1159:68:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/airflow/.local/lib/python3.8/site-packages/flatterer/__init__.py", line 141, in flatten
    flatten_rs(input, output_dir, csv, xlsx, sqlite, parquet,
RuntimeError:

Caused by:
    sending on a disconnected channel
```

Then, I removed the `only_fields=True` argument:
```
flatten('s3://<path-redacted>.jsonl.gz', '/tmp/unnest', force=True, tables_csv='/tmp/tables.csv, only_tables=True, fields_csv='/tmp/fields.csv', ndjson=True)
```
And this time data was successfully flattened. Why would `only_fields=True` cause it to fail?

**Comment by tianchen98** [comment]
I'm using the original `fields.csv` that flatterer produces, no changes are made to it. The environment is AWS EKS ver. 1.24

**Comment by kindly** [comment]
@tianchen98 there have been some recent changes that fix some edge cases with only_fields and only_tables.  Even so, I would only use them one at a time as I think there are still some edge cases using them both.  `only_fields` with a `fields.csv` should cover any case that you need if you remove all of a tables fields.
