### ISSUE TITLE
parquet output does not use field_title

### ISSUE THREAD

**Issue by awendland** [kindly/flatterer#70]
First off, thank you so much for making this library! It is performant and ergonomic. It's amazing! I was hand coding flattening logic myself which was hard to manage. This library has been such a joy to work with instead.

Secondly, I believe I found a small bug. The `field_title` is not being respected in the parquet output.

**Reproduction**

sample.json
```json
{
    "a1": "val_a1",
    "a2": [
        {"b1": "val_b1", "b2": "val_b2"}
    ]
}
```

fields.csv
```csv
table_name,field_name,field_title
main,_link,_link
main,b2,b2
main,b1,b1_new_name
```

_notice `b1_new_name` and the reordering putting `b2` first__

command
```
flatterer ../sample.json sample/ -p a2 --parquet --fields=fields.csv --force
```

**Expected Behavior**

sample/parquet/main.parquet will have columns `_link`, `b2`, and `b1_new_name`, like the CSV file.

**Actual Behavior**

sample/parquet/main.parquet has columns `_link`, `b2`, and `b1`. The ordering is respected but the new `field_title` for `b1_new_name` is not.

The CSV file, however, get's it correct:

```csv
_link,b2,b1_new_name
0,val_b2,val_b1
```

**Version**

`0.19.18`. Tested in Python and via CLI. Installed via `pip`.

**Comment by kindly** [comment]
Thanks for the detailed issue. This was missed for some reason and was only using the name not the title for parquet. This has now been fixed in the latest version.
